version: 0.2

env:
  variables:
    MAIN_BUCKET: simaptics.com
    MODE: production

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies for simaptics...
      - npm ci

  build:
    commands:
      - echo Building simaptics...
      - npx vite build --mode=$MODE

  post_build:
    commands:
      - echo Deploying dice...
      - aws s3 sync build/ s3://$MAIN_BUCKET --delete

artifacts:
  files: []
